version: '3.8'

services:
  # Frontend Production
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./apps/frontend/.env.production
    depends_on:
      - backend
    networks:
      - nexnest-monorepo-starter-network

  # Backend Production
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./apps/backend/.env.production
    depends_on:
      - mongo
    networks:
      - nexnest-monorepo-starter-network

  # MongoDB Production
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nexnest-monorepo-starter
    networks:
      - nexnest-monorepo-starter-network

  # Redis Production
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - nexnest-monorepo-starter-network

volumes:
  mongo_data:
  redis_data:

networks:
  nexnest-monorepo-starter-network:
    driver: bridge
