version: '3.8'

services:
  # Frontend Development
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./apps/frontend/.env.local
    depends_on:
      - backend
    networks:
      - nexnest-monorepo-starter-network

  # Backend Development
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      - /app/dist
    env_file:
      - ./apps/backend/.env.local
    depends_on:
      - mongo
    networks:
      - nexnest-monorepo-starter-network

  # MongoDB for Development
  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nexnest-monorepo-starter
    networks:
      - nexnest-monorepo-starter-network

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nexnest-monorepo-starter-network

volumes:
  mongo_data:
  redis_data:

networks:
  nexnest-monorepo-starter-network:
    driver: bridge
